---
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ensure all .sh scripts are executable
        run: |
          for f in $(find . -type f -name '*.sh'); do
            if ! [ -x "$f" ]; then
              echo "Script $f is not executable!" && exit 1
            fi
          done
      - name: Check Bash version
        run: |
          bash --version | grep -q 'version [4-9]' || (echo 'Bash 4+ required' && exit 1)
      - name: Run dependency check
        run: |
          ./bin/check-deps
      - name: Lint scripts with ShellCheck
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck
          shellcheck -x $(find . -type f -name '*.sh')
      - name: Check sourced scripts existence
        run: |
          for f in $(grep -hoP "source +['\"]?\K[^ '\"]+" $(find . -type f -name '*.sh') | sort -u); do
            if ! [ -f "$f" ]; then
              echo "Sourced script $f does not exist!" && exit 1
            fi
          done
      - name: Run integration tests
        run: |
          set -euo pipefail
          sudo ./run-tests.sh
