name: ShellCheck
on:
  push:
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'
  schedule:
    - cron: '0 3 * * 1' # roda toda segunda-feira às 03:00 UTC
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run ShellCheck
        run: |
          shellcheck -x $(find . -type f -name '*.sh')
      - name: Check sourced scripts existence
        run: |
          for f in $(grep -hoP "source +['\"]?\K[^ '\"]+" $(find . -type f -name '*.sh') | sort -u); do
            if ! [ -f "$f" ]; then
              echo "Sourced script $f does not exist!" && exit 1
            fi
          done
